# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [15]:
import numpy as np
print (np.__version__)

1.23.5


2) Создать нулевой вектор размера 10

In [3]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [13]:
b = 7*np.ones(7)
print(b)

[7. 7. 7. 7. 7. 7. 7.]


4) Создать вектор заполненный четными числами от 10 до 100

In [23]:
c = np.arange(10, 101, 2)
print(c)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [39]:
t = np.random.rand(5)
t1 = np.flip(t)
print('Массив случайных чисел',t)
print('Развернутый вид',t1)

Массив случайных чисел [0.47025466 0.52698624 0.57859105 0.12982305 0.17459117]
Развернутый вид [0.17459117 0.12982305 0.57859105 0.52698624 0.47025466]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [50]:
a=np.array(range(0,9))
b=a.reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [52]:
np.eye(4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [54]:
m = np.full((4,4), 7)
np.fill_diagonal(m, [1, 2, 3, 4])
print(m)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [55]:
n = np.zeros((5,5))
for i in range(5):
  n[i] = np.arange(5)
print(n)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [58]:
p = np.random.rand(10, 10)
mean1 = np.mean(p, axis = 1)
p -= mean1.reshape(-1, 1)
print(p)

[[-0.36350826  0.35227653  0.04534857 -0.16245083 -0.45942697 -0.14008582
   0.48524499 -0.19289449  0.02748255  0.40801373]
 [ 0.20252837  0.15571767  0.22706459 -0.31688003  0.12258293  0.20856784
  -0.39427128  0.33557106 -0.32758504 -0.21329611]
 [-0.11072692  0.28735494  0.30783908  0.4417006  -0.28634872 -0.47591878
   0.22323374 -0.40814479  0.38879847 -0.36778763]
 [ 0.21560518  0.27941184  0.34027772 -0.46715424 -0.47591723  0.30693858
  -0.20017101  0.2513983   0.11657478 -0.36696393]
 [-0.09990828  0.06386649 -0.25970139  0.11676711 -0.02845303  0.10961358
   0.22199618 -0.01722335  0.2002489  -0.30720622]
 [-0.33961268  0.26831674  0.05274389  0.10294394  0.2211873   0.06225138
  -0.16297343  0.11117893 -0.48830675  0.17227069]
 [-0.41114107  0.11421499 -0.4285343  -0.36545894  0.12360082 -0.26281351
   0.22074933  0.29654143  0.31571411  0.39712711]
 [ 0.3052074  -0.25656041  0.42155397  0.30828372 -0.33103934 -0.37193413
  -0.34249756 -0.17721374  0.16509215  0.27910794]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
i = np.random.rand(10, 10)
median1 = np.median(i, axis = 0)
i -= median1
print(i)

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
q = np.random.rand(5, 5)
f_min = np.min(q, axis = 1)
f_max = np.max(q, axis = 1)
q = np.column_stack((q, f_min, f_max))
print(q)

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [60]:
from os import WNOWAIT
w = np.arange(1, 52)
w1 = w[w % 2 == 0]
w2 = w[w % 2 != 1]

ww1 = w1.reshape(5,5)
ww2 = w2.reshape(5,5)

ww = np.dot(ww1, ww2)

print(ww)

[[ 860  920  980 1040 1100]
 [1960 2120 2280 2440 2600]
 [3060 3320 3580 3840 4100]
 [4160 4520 4880 5240 5600]
 [5260 5720 6180 6640 7100]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [62]:
v = np.zeros((8, 8))
v[::2, ::2] = 1
v[1::2, 1::2] = 1
print(v)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
