# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy as np
print (np.__version__)

1.23.5


2) Создать нулевой вектор размера 10

In [ ]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [ ]:
b = np.ones(7)*7
print(b)

[7. 7. 7. 7. 7. 7. 7.]


4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
c = np.arange(10, 101, 2)
print(c)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
d = np.random.rand(10)
d2 = np.flip(d)
print(d, d2)

[0.00454993 0.7311472  0.11362342 0.67789099 0.88231069 0.29646335
 0.93780968 0.31162322 0.35128625 0.8803668 ] [0.8803668  0.35128625 0.31162322 0.93780968 0.29646335 0.88231069
 0.67789099 0.11362342 0.7311472  0.00454993]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
aa = np.arange(9).reshape(3,3)
print(aa)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
np.eye(4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
bb = np.full((4,4), 7)
np.fill_diagonal(bb, [1, 2, 3, 4])
print(bb)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
cc = np.zeros((5,5))
for i in range(5):
  cc[i] = np.arange(5)
print(cc)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
dd = np.random.rand(10, 10)
mean1 = np.mean(dd, axis = 1)
dd -= mean1.reshape(-1, 1)
print(dd)

[[-0.03307282  0.18931483 -0.31562086  0.4233941  -0.08995171 -0.32778556
   0.16857717  0.21701667 -0.09807093 -0.13380088]
 [ 0.24582301 -0.20110732  0.26502368  0.3890995   0.28900293 -0.15720436
  -0.14399745 -0.31403241  0.08038647 -0.45299405]
 [ 0.26576302 -0.29555224 -0.06858999 -0.07787733  0.15083689  0.1741797
   0.22278892 -0.07223611 -0.19523849 -0.10407436]
 [-0.57319252 -0.08518633 -0.10089319 -0.38401722  0.4221533   0.31860057
  -0.12748743  0.39339608 -0.27607266  0.41269941]
 [-0.27449134 -0.33137682  0.27023737  0.37142232 -0.4591889  -0.20572541
   0.01828842  0.36167109 -0.20434473  0.45350801]
 [ 0.10113013  0.14136371 -0.10076076 -0.34737551  0.34471727  0.20121993
  -0.57764398 -0.17928383  0.20776029  0.20887274]
 [ 0.36246494 -0.1591174  -0.36029755  0.46365883  0.13274653  0.24220756
  -0.04325517 -0.37652828  0.06236152 -0.32424098]
 [-0.21480012  0.40690734 -0.03520882  0.57973104 -0.26419676 -0.28059114
  -0.32826394 -0.23748437 -0.00303264  0.3769394 ]
 

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
ee = np.random.rand(10, 10)
median1 = np.median(ee, axis = 0)
ee -= median1
print(ee)

[[ 0.45895606 -0.38026699  0.31265    -0.13748918 -0.51177328 -0.16100767
   0.19420113 -0.13983134  0.25988964  0.06594908]
 [ 0.40699322 -0.30584433 -0.1808709  -0.63411222 -0.24205173  0.01144802
   0.07226369  0.52630696  0.23739645  0.37641817]
 [-0.09558115 -0.35925165  0.2160147   0.06040166  0.22955666 -0.36885983
   0.29224652  0.24949536 -0.10866641  0.31214479]
 [-0.02013964  0.00093559 -0.04631671 -0.03983604  0.28777731 -0.17381036
  -0.19623345 -0.04744229 -0.23408654 -0.28092599]
 [-0.36366194  0.06682263 -0.4274235   0.31624638 -0.0048585   0.17996572
   0.37642609 -0.31905975 -0.383848   -0.06594908]
 [-0.37074915  0.0070306  -0.55310481  0.03983604  0.1779163  -0.01144802
  -0.35388686  0.16933695  0.22546324  0.31289134]
 [ 0.00749216 -0.00093559  0.04631671  0.11770787 -0.00790023  0.15176065
  -0.48940782 -0.09494848 -0.3546854   0.35100226]
 [ 0.16603491 -0.59928269 -0.36700745 -0.63385456  0.0048585   0.20555102
  -0.07480189  0.04744229  0.39078622 -0.41761539]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
ff = np.random.rand(5, 5)
f_min = np.min(ff, axis = 1)
f_max = np.max(ff, axis = 1)
ff = np.column_stack((ff, f_min, f_max))
print(ff)

[[3.19482317e-02 7.70996978e-01 6.75091051e-01 2.39458773e-01
  8.63541855e-01 3.19482317e-02 8.63541855e-01]
 [9.62317530e-01 5.79467283e-01 6.95238388e-04 5.84767444e-01
  2.33640478e-01 6.95238388e-04 9.62317530e-01]
 [8.39087480e-01 4.08273257e-01 8.26413847e-01 7.08966895e-01
  4.26635412e-01 4.08273257e-01 8.39087480e-01]
 [7.63680004e-01 1.44452510e-01 8.07991822e-02 2.30077666e-01
  5.46468483e-01 8.07991822e-02 7.63680004e-01]
 [4.21532087e-01 7.02784946e-02 5.12084310e-01 6.81183208e-01
  9.05610003e-01 7.02784946e-02 9.05610003e-01]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [ ]:
g = np.arange(1, 52)
g1 = g[g % 2 == 0]
g2 = g[g % 2 != 1]

gg1 = g1.reshape(5,5)
gg2 = g2.reshape(5,5)

gg = np.dot(gg1, gg2)

print(gg)

[[ 860  920  980 1040 1100]
 [1960 2120 2280 2440 2600]
 [3060 3320 3580 3840 4100]
 [4160 4520 4880 5240 5600]
 [5260 5720 6180 6640 7100]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
hh = np.zeros((8, 8))
hh[::2, ::2] = 1
hh[1::2, 1::2] = 1
print(hh)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
